# Generated by Django 3.1.7 on 2021-06-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
            ],
        ),
    ]
